### ISSUE TITLE
Change Thailand to a single region 

### ISSUE THREAD

**Issue by trevorb1** [Electricity-Transmission-Database/electricity-transmission-database#9]
Update the global shapefile creation for thailand to be a single node. The database file will also need to be updated with this.

**Comment by trevorb1** [comment]
FYI @maartenbrinkerink @amanmajid

**Comment by maartenbrinkerink** [comment]
@trevorb1 I updated the database file to the latest version (with old THA lines removed and new THA lines added) and updated the nodes.csv file. I think that only leaves the shapefile that needs to be updated (no clue how to do that).
